language: generic
os:
  - linux
notifications:
  email: true

before_install:
  - wget https://github.com/leanprover-community/lean/releases/download/v3.17.1/lean-3.17.1-linux.tar.gz -O lean.tgz
  - mkdir lean
  - tar xzf lean.tgz -C lean --strip-components=1
  - export PATH=$PATH:`pwd`/lean/bin

install:
  - mkdir groupoid
  - cd groupoid
  - git clone https://github.com/groupoid/lean
  - cd ..
  - export LEAN_PATH="`pwd`/lean/lib/lean/library:`pwd`/groupoid/lean"
  - lean --make groupoid/lean/ground_zero
